# docker-compose.yml
version: '3'

volumes:
  foodgram_pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static/

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    depends_on:
      - backend
      - frontend
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/static/
    ports:
      - 8000:80