# version: '3.3'
# services:

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

version: '3' 
volumes: 

  pg_data: 
  static: 
  media: 

services: 

  db: 
    image: postgres:13 
    env_file: .env 
    volumes: 
      - pg_data:/var/lib/postgresql/data 

  backend: 
    depends_on: 
      - db 
    build: ./backend/ 
    env_file: .env 
    volumes: 
      - static:/backend_static/ 
      - media:/app/media/ 

  frontend: 
    env_file: .env 
    build: ./frontend/ 
    command: cp -r /app/build/. /frontend_static/ 
    volumes: 
      - static:/static/ 

  gateway: 
    depends_on: 
      - backend 
    build: ./nginx/ 
    env_file: .env 
    ports: 
      - 9000:80 
    volumes: 
      - static:/static/ 
      - media:/app/media/ 